export const STORES_STATES=[
    { "menuValue": "CA", "menuName": "CA" },
    { "menuValue": "AZ", "menuName": "AZ" },
    { "menuValue": "TX", "menuName": "TX" },
    { "menuValue": "GA", "menuName": "GA" },
    { "menuValue": "TN", "menuName": "TN" },
    { "menuValue": "NY", "menuName": "NY" },
    { "menuValue": "CO", "menuName": "CO" },
    { "menuValue": "PA", "menuName": "PA" },
    { "menuValue": "MA", "menuName": "MA" },
    { "menuValue": "OR", "menuName": "OR" },
    { "menuValue": "IL", "menuName": "IL" },
    { "menuValue": "NV", "menuName": "NV" },
    { "menuValue": "WA", "menuName": "WA" },
    { "menuValue": "FL", "menuName": "FL" },
    { "menuValue": "NC", "menuName": "NC" },
    { "menuValue": "MI", "menuName": "MI" },
    { "menuValue": "OH", "menuName": "OH" },
    { "menuValue": "VA", "menuName": "VA" },
    { "menuValue": "NJ", "menuName": "NJ" },
    { "menuValue": "MO", "menuName": "MO" },
    { "menuValue": "WI", "menuName": "WI" },
    { "menuValue": "MN", "menuName": "MN" },
    { "menuValue": "IN", "menuName": "IN" },
    { "menuValue": "SC", "menuName": "SC" },
    { "menuValue": "KY", "menuName": "KY" },
    { "menuValue": "AL", "menuName": "AL" },
    { "menuValue": "LA", "menuName": "LA" },
    { "menuValue": "OK", "menuName": "OK" },
    { "menuValue": "KS", "menuName": "KS" },
    { "menuValue": "AR", "menuName": "AR" },
    { "menuValue": "MS", "menuName": "MS" },
    { "menuValue": "NM", "menuName": "NM" },
    { "menuValue": "NE", "menuName": "NE" },
    { "menuValue": "WV", "menuName": "WV" },
    { "menuValue": "NH", "menuName": "NH" },
    { "menuValue": "ID", "menuName": "ID" },
    { "menuValue": "ME", "menuName": "ME" },
    { "menuValue": "MT", "menuName": "MT" },
    { "menuValue": "RI", "menuName": "RI" },
    { "menuValue": "DE", "menuName": "DE" },
    { "menuValue": "SD", "menuName": "SD" },
    { "menuValue": "ND", "menuName": "ND" },
    { "menuValue": "AK", "menuName": "AK" },
    { "menuValue": "VT", "menuName": "VT" },
    { "menuValue": "WY", "menuName": "WY" }
  ]
  
  export const STORES_CITIES = [
    { "menuValue": "San Francisco", "menuName": "San Francisco" },
    { "menuValue": "Phoenix", "menuName": "Phoenix" },
    { "menuValue": "Dallas", "menuName": "Dallas" },
    { "menuValue": "Atlanta", "menuName": "Atlanta" },
    { "menuValue": "Nashville", "menuName": "Nashville" },
    { "menuValue": "New York", "menuName": "New York" },
    { "menuValue": "Denver", "menuName": "Denver" },
    { "menuValue": "Philadelphia", "menuName": "Philadelphia" },
    { "menuValue": "Boston", "menuName": "Boston" },
    { "menuValue": "Austin", "menuName": "Austin" },
    { "menuValue": "Los Angeles", "menuName": "Los Angeles" },
    { "menuValue": "Houston", "menuName": "Houston" },
    { "menuValue": "Portland", "menuName": "Portland" },
    { "menuValue": "Chicago", "menuName": "Chicago" },
    { "menuValue": "Las Vegas", "menuName": "Las Vegas" },
    { "menuValue": "Seattle", "menuName": "Seattle" },
    { "menuValue": "Miami", "menuName": "Miami" },
    { "menuValue": "San Diego", "menuName": "San Diego" },
    { "menuValue": "Charlotte", "menuName": "Charlotte" },
    { "menuValue": "Detroit", "menuName": "Detroit" }
];
